version: 1
services:
  - type: web
    name: flask-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python flask_server.py
    envVars:
      FLASK_ENV: development
